# Generated by Django 3.0.6 on 2020-05-21 09:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=250, unique=True)),
                ('title', models.CharField(max_length=250)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('company', models.CharField(max_length=250)),
                ('compensation', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
    ]
